### PR TITLE
fix(template): added no-legacy-stdTx flag

### PR DESCRIPTION
**Pull request by marinhoarthur**
Related issues:

[Legacy endpoint /txs with stargate v0.44 keplr transaction fails with basic send-token](https://github.com/chainapsis/keplr-extension/issues/167)

[Signing transactions with Keplr error](https://github.com/tendermint/vue/issues/128)

### CODE REVIEW

**Comment by fadeev** [comment]
@marinhoarthur does this PR fixes https://github.com/tendermint/vue/issues/128?

**Comment by marinhoarthur** [comment]
@fadeev yes

**Review by Matthews3301 — APPROVED** [review]
Verified, this solves the problem.

**Review by mihailmarcu — APPROVED** [review]
Hey @marinhoarthur,
After our session where we reproduced the issue and tested the final fix I can tell that your solution fixed this error. 

You can easily go and merge the changes. 

#### Checklist when testing a PR

- [x] Code review
- [x] The bug was reproduced locally
- [x] Manual testing performed
- [x] Changes made fixed the bug
- [x] No potential merge conflicts with develop

**Pull request merged**
