### PR TITLE
feat: Add slot to override navbar logo

### PR DESCRIPTION
**Pull request by mikeeus**
Adds a prop called logo of type NavbarLogo that lets the user override the default logo.
Addresses #238

### CODE REVIEW

**Comment by marinhoarthur** [comment]
@mihailmarcu please review.

**Comment by mihailmarcu** [comment]
Hey @marinhoarthur, @mikeeus,
The best way to implement such functionality is definitely not props. I think the best solution here is #slots. This will allow us to change not only the logo but also the structure, this solution using props does not allow you to use the svg code directly and manipulate with colors etc.

Also, some developers will want to have different dark theme images or use the `figure` tag.

**Comment by mikeeus** [comment]
@mihailmarcu That's a great idea! I've updated the PR to replace the `<router-link>` with a named slot called logo.
Is that what you had in mind?

**Review by mihailmarcu — APPROVED** [review]
Hey @mikeeus,
Thanks for your input on improving the navigation bar component. The changes look good on our end.

**Comment by fadeev** [comment]
@marinhoarthur can you, please, review, so we can merge if it looks good. Thanks!

**Review by marinhoarthur — APPROVED** [review]

**Comment by marinhoarthur** [comment]
closes #238

**Pull request merged**
