### PR TITLE
test: implement initial setup

### PR DESCRIPTION
**Pull request by 0xb4rt**
Hello,

This PR implements a basic test file using `@vue/test-utils` and `jest`.

### CODE REVIEW

**Review by fadeev — APPROVED** [review]
Thank you for contributing, @0xb4rt 🚀 We definitely want (and need) to start writing tests 🙂

@clockworkgr is maintaining this repo and he will review this PR as soon as gets online.

**Comment by clockworkgr** [comment]
Thanks for the contribution @0xb4rt . Can you please also commit the updated package.json for the test-utils/jest framework as well?

**Comment by 0xb4rt** [comment]
Ops my bad, here you go!

**Comment by fadeev** [comment]
This has become out of date.

**Pull request closed without merging**
