### PR TITLE
Stargate Integration

### PR DESCRIPTION
**Pull request by vince19972**
### Description
- [x] Use gRPC gateway endpoint to fetch decoded tx value
- [x] Create fallback tx formatter for Launchpad version

### Todos
- [x] Understand why `gas_wanted`, `gas_used`, and `events` are missing from the decoded tx response
- [x] Resolve the failed tx fetching issue (#30)
- [x] Wait for [gRPC supports](https://github.com/tendermint/starport/pull/400) merged in Starport

### Notes
- Temporarily combining responses from two endpoints (RPC query and gRPC gateway) to get all required info.
- ~~Temporarily using `26657/tx?hash=0x{txhash}` endpoint to fetch tx instead of gRPC gateway, because of the inconsistent TxResponse format. Although this endpoint response is lack of `memo` and `fee` too.~~

### CODE REVIEW

**Comment by fadeev** [comment]
Just trying it out with Stargate.

Screenshot 2020-11-10 at 12 56 22

**Comment by vince19972** [comment]
Hey @fadeev , so each of two endpoints to fetch tx response has its own defects at this moment. 

For gRPC gateway, the most critical drawback is incapability to identify unsuccessful tx, along with minor issues such as lack of `gas` info. On the other hand, `tx?hash=0x{hash}` query doesn't get `memo` and `fee` info back. 

Any thoughts on which way to go?

**Comment by fadeev** [comment]
Let's use both then! 🙂 (unless there are hidden downsides of doing that, of course)

**Comment by vince19972** [comment]
> Let's use both then! 🙂 (unless there are hidden downsides of doing that, of course)

I guess the only drawback, which can totally be ignored for now, is performance issue. But yea, I'll work on combining them now!

**Review by fadeev — CHANGES_REQUESTED** [review]
Checking it out!

Can you, please, import `lodash`.

```
/Users/fadeev/github.com/tendermint/vue/src/components/SpBlockExplorer/BlockChain.vue
  211:22  error  '_' is not defined  no-undef
```

**Comment by fadeev** [comment]
Also, I see how having both a directory and a component with a same name might be confusing, so if you don't mind, please, move `SpBlockExplorer.vue` into `SpBlockExplorer/`. Thanks!

**Comment by fadeev** [comment]
I've tried adding a block explorer component into `Index.vue`. Blocks are streaming, but as soon as I `appd tx foo create-post...`, it errors out. Please, just try running it with a scaffolded Stargate app to check that it works.

Screenshot 2020-11-12 at 23 55 44

**Comment by vince19972** [comment]
Hmmm it's working on my end. Looks like the gRPC gateway is not implemented in the error though. Are you using the latest Starport that Ilker merged with [gRPC supports](https://github.com/tendermint/starport/pull/400) few days ago?

**Review by fadeev — APPROVED** [review]
👍

**Pull request merged**
