### PR TITLE
new stack for bundling / new scripts for dev env

### PR DESCRIPTION
**Pull request by marinhoarthur**
Refactored bundling:

- `@starport/vue` webpack -> rollup
- `@starport/vuex` babel -> rollup
- `@starport/template` webpack -> vite

New scripts

- `npm run dev:watch` to build-watch `@starport/vue` and `@starport/vuex`
- `npm run dev:serve` to serve `@starport/template`

Moved SPClient

- moved  `@starport/client-js` into `@starport/vuex`

### CODE REVIEW

**Comment by marinhoarthur** [comment]
closes #91 #144

**Comment by fadeev** [comment]
This looks great! One question I have is, should we add Vite as a dev dependency of the monorepo, so that running `npm i && npm run dev:serve` at the top-level produces expected results. Seems like right now I have to go into the template dir, install deps there and go back to the top to run serve.

**Comment by fadeev** [comment]
Right now I'm getting:

```
tendermint/vue % npm run dev:serve

> dev:serve
> lerna exec --parallel --scope='@starport/template' -- npm run dev

lerna notice cli v4.0.0
lerna notice filter including "@starport/template"
lerna info filter [ '@starport/template' ]
lerna info Executing command in 1 package: "npm run dev"
@starport/template: > @starport/template@0.1.54 dev
@starport/template: > vite
@starport/template: error when starting dev server:
@starport/template: Error: The following dependencies are imported but could not be resolved:
@starport/template:   @starport/vue/lib/style.css (imported by /Users/fadeev/github.com/tendermint/vue/packages/template/src/App.vue)
@starport/template: Are they installed?
@starport/template:     at optimizeDeps (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:64210:15)
@starport/template:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@starport/template:     at async runOptimize (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:68225:48)
@starport/template:     at async Server.httpServer.listen (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:68241:21)
lerna ERR! npm run dev exited 1 in '@starport/template'
lerna ERR! npm run dev stdout:

> @starport/template@0.1.54 dev
> vite

lerna ERR! npm run dev stderr:
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @starport/vue/lib/style.css (imported by /Users/fadeev/github.com/tendermint/vue/packages/template/src/App.vue)

Are they installed?
    at optimizeDeps (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:64210:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:68225:48)
    at async Server.httpServer.listen (/Users/fadeev/github.com/tendermint/vue/packages/template/node_modules/vite/dist/node/chunks/dep-4a9cff06.js:68241:21)
lerna ERR! npm run dev exited 1 in '@starport/template'
```

```
tendermint/vue % node -v
v16.13.1
```

(doesn't work with 17 either)

**Comment by marinhoarthur** [comment]
There are two steps so that the packages are up-and-running.

1. `npm run dev:watch` to bootstrap the entire repo (npm install & symlinking of packages)
2. `npm run dev:serve` to serve the local server of `@starport/template`

Your lacking of vite will be fixed after step 1. 

The second error is due to `@starport/template` having installed a public release of `@starport/vue`  and not a local one (local one has `style.css`, public one has a different file for styling). This is not going to happen after step 1 as well (symlinking).

Note that steps 1 and 2 need each one its own terminal as they keep watching for changes.

**Review by fadeev — APPROVED** [review]
It's almost instant! Great work! 🙌

**Pull request merged**
