### PR TITLE
fix: search position

### LINKED ISSUE #215: fix(ui): search bar is misaligned (assets list)
Currently:

Screenshot 2022-02-19 at 12 25 19

Screenshot 2022-02-19 at 12 23 32

Should be:

Screenshot 2022-02-19 at 12 26 29

Screenshot 2022-02-19 at 12 26 56

### PR DESCRIPTION
**Pull request by mihailmarcu**
## Description & Context

The search bar was not aligned like in the figma design.

## How To Test

1. Connect Wallet;
2. "Assets" component must have a search field after a successful data request;
3.  Default state and focus state must be properly aligned

## Linked issue

Closes #215

### CODE REVIEW

**Comment by marinhoarthur** [comment]
Text is still not vertically aligned. Figma says it should.

branch =
image

figma =
image

Is this ok w/ Design?

**Comment by fadeev** [comment]
The goal is to have it aligned perfectly.

**Comment by mihailmarcu** [comment]
Hey @marinhoarthur,
Let me check, but I aligned the focus state using the pixel perfect extension.

**Comment by mihailmarcu** [comment]
The problem is in the design itself. Default state and focus state are aligned differently.

**Comment by mihailmarcu** [comment]
Hey @marinhoarthur,
The issue is returned back for review after the changes match the latest Figma updates.

**Review by marinhoarthur — APPROVED** [review]

**Pull request merged**
