### PR TITLE
Storybook Vuex support

### PR DESCRIPTION
**Pull request by shapkarin**
Without such addition `this.$store` and `useState()` is undefined in components used in stories and storybook return exception on each `this.$store...` call, for example at `this.$store.hasModule` – that defined in beforeCreate at almost any @starport/vue component.

Mainly it's just updated`packages/storybook/.storybook/preview.js` that include vuex and store. And `./packages/storybook/src/store` with generated and `./packages/vuex` modules.

---

I think it should import`./package/vuex` modules explicitly, instead of `npm link` with `@starport/vuex`.
At this moment it just use npm link, but maybe it's reasonable just to import vuex modules from `./packages/vuex` or to use `webpack aliases` instead of `npm link`.

The next thing should be done is fix compiling in case of component use optional chaining or nullish coalescing.

### CODE REVIEW

**Comment by shapkarin** [comment]
Will make this PR more clean in 10 min

**Comment by shapkarin** [comment]
It may be reasonable to add `generated` store to the gitignore..
Screenshot 2021-08-16 at 11 24 42

**Comment by fadeev** [comment]
@shapkarin we're not gitignoring `generated`, because it's a part of the template. When we scaffold a chain, we scaffold the Vue template. If we generated stores at the time of scaffolding, it would slow down the whole process dramatically. Hence, we're "precompiling" generated stores as an optimization. (since we know the exact version of Cosmos SDK we scaffold the chain with, it's pretty reliable).

**Comment by shapkarin** [comment]
Will prepare the next PR soon https://github.com/tendermint/vue/compare/develop...shapkarin:storyWithVuexState with `SpWallet` and `SpTokenSend` that use `Vuex` state

**Comment by shapkarin** [comment]
@fadeev add commit with env init, add story SpBlocksTable that shows new blocks in realtime and SpWallet story. The last one is not so useful, but docs can be added. 
Keep in mind that to use testnet .env file should be present.
Also I removed store/generated and use the same one from packages/template. Current me if it's wrong and I should keep it.

**Comment by fadeev** [comment]
Thanks for your contribution @shapkarin 👍 Looks good, but before this can be merged, the Netlify build has to be fixed:

https://gist.github.com/fadeev/5d61da71f557b7dd2abfa222eca86a94

**Comment by fadeev** [comment]
Stale PR, closing for now.

**Pull request closed without merging**
