### PR TITLE
repo overall refresh

### PR DESCRIPTION
**Pull request by marinhoarthur**
- New bundling stack
- Overall housekeeping

Refer to #155

### CODE REVIEW

**Comment by Matthews3301** [comment]
@marinhoarthur sorry, getting error `[vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?` when running `npm run dev` on template package. Can this be run before being used by a specific chain?

**Comment by marinhoarthur** [comment]
> @marinhoarthur sorry, getting error `[vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?` when running `npm run dev` on template package. Can this be run before being used by a specific chain?

Which commands you executed?

**Comment by Matthews3301** [comment]
@marinhoarthur `npm install` `npm run dev`

**Comment by marinhoarthur** [comment]
Both `rollup-plugin-sass` and `vite` have `sass` as a dependency. How is your `node_modules` looking like?

**Comment by clockworkgr** [comment]
sass needs to be added as a devDependency.... `template` does not have `rollup-plugin-sass`

**Comment by marinhoarthur** [comment]
this is my `npm ls sass`

image

**Comment by marinhoarthur** [comment]
> Both `rollup-plugin-sass` and `vite` have `sass` as a dependency. How is your `node_modules` looking like?


> @marinhoarthur `npm install` `npm run dev`

please take a look [here](https://github.com/tendermint/vue/pull/155#issuecomment-1002063741) on how to get the new stuff

**Pull request merged**
