### PR TITLE
feat: Add sign in with Keplr functionality 

### PR DESCRIPTION
**Pull request by clockworkgr**

### CODE REVIEW

**Comment by fadeev** [comment]
What's the best way to check this out? 🙂

**Comment by clockworkgr** [comment]
still the npm link method  I'm afraid...havent got to that issue yet

**Comment by fadeev** [comment]
It throws `TypeError: Cannot read property 'bond_denom' of undefined` when I click on Keplr, but it might be because this branch doesn't include fixes from develop.

**Comment by clockworkgr** [comment]
> It throws `TypeError: Cannot read property 'bond_denom' of undefined` when I click on Keplr, but it might be because this branch doesn't include fixes from develop.

hmmm...
have you linked vuex as well?

**Review by fadeev — APPROVED** [review]
Great work!

**Comment by fadeev** [comment]
I used to work locally when I approved, but now using https://github.com/tendermint/starport/pull/944 when I press "Access wallet", it throws `TypeError: Cannot read property 'keplr' of undefined`.

```
console.log(window.keplr)
t.InjectedKeplr {version: "0.8.3", enigmaUtils: Map(0)}
```

fwiw seems like Keplr is injected ok.

**Comment by clockworkgr** [comment]
needs this: https://github.com/tendermint/starport/pull/925/commits/62470cecc61c3b0f55e8a953f025acff9ac0358a

(essentially add window to the vue globals in the template's main.js file)

**Comment by fadeev** [comment]
Can we instead of modifying the template, use `window.keplr`? It is available after all.

**Comment by clockworkgr** [comment]
Not entirely sure when/where it's available...Def isn't inside the template....Try this next commit

**Review by fadeev — APPROVED** [review]
Works for me, great work!

**Review by fadeev — APPROVED** [review]

**Pull request merged**
