### PR TITLE
chore: added a readme with a cover image

### LINKED ISSUE #212: docs: add a readme
Add a temporary readme that briefly describes what goes on in this repo.

### PR DESCRIPTION
**Pull request by fadeev**

### CODE REVIEW

**Review by barriebyron — APPROVED** [review]
let's use Sentence case capitalization 

@fadeev  did you want me to create a contributing.md file for this repo instead of including a short contributing mention in the readme?

did you want a lowercase readme.md filename to match our other repos?

**Comment by marinhoarthur** [comment]
@fadeev please add `npm install` before `npm run dev`

**Comment by fadeev** [comment]
Added `npm install` and switched to `readme.md`. Thanks!

**Comment by fadeev** [comment]
@barriebyron we can add a contributing guideline in a separate PR. Thanks for the suggestion!

**Review by mihailmarcu — APPROVED** [review]

**Pull request merged**
