### PR TITLE
handling decimals

### PR DESCRIPTION
**Pull request by marinhoarthur**
For now we're going to disallow decimals. We need to query denom precision so to proper handle each token.

### CODE REVIEW

**Comment by marinhoarthur** [comment]
`SpAmountInput` is copy/paste from [Emeris](https://github.com/allinbits/demeris/blob/develop/src/components/ui/AmountInput.vue)

**Comment by fadeev** [comment]
@mihailmarcu please, review.

**Comment by fadeev** [comment]
A nice improvement from a users' point of view 👍

**Review by mihailmarcu — APPROVED** [review]
Hey @marinhoarthur,

The functionality is working properly and I can use decimals for amount input. Correct me if I'm wrong, but in the future this may be included in a separate composable.

**Comment by marinhoarthur** [comment]
> Hey @marinhoarthur,
> 
> The functionality is working properly and I can use decimals for amount input. Correct me if I'm wrong, but in the future this may be included in a separate composable.

We need to have a solid API for handling amounts. Composables could def help us achieve that!

**Pull request merged**
