### PR TITLE
Refactor: Port packages/vue to typescript

### PR DESCRIPTION
**Pull request by clockworkgr**

### CODE REVIEW

**Comment by fadeev** [comment]
Never seen this before:

https://github.com/tendermint/vue/blob/refactor/vue-typescript/packages/vue/src/Starport%20Interface.json

Is it an icon library that uses this file? Should we, perhaps, call it differently?

**Comment by clockworkgr** [comment]
> Never seen this before:
> 
> https://github.com/tendermint/vue/blob/refactor/vue-typescript/packages/vue/src/Starport%20Interface.json
> 
> Is it an icon library that uses this file? Should we, perhaps, call it differently?

Yeah, it's the icomoon icon font definitions.

**Review by fadeev — APPROVED** [review]
Haven't tested this, but overall this looks great! We will have to figure out all the details re how to deal with TS types, but, yeah, 👍

**Comment by clockworkgr** [comment]
It worked for me :p

Will be doing some refactoring and polishing on vuex as well then I'll work on a couple of action workflows to make testing and releasing easier

**Pull request merged**
